#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
cd ~/app-root/repo/ 
mvn clean install -Dmaven.test.skip=true -Duser.home=$OPENSHIFT_DATA_DIR
cd ~/
gear start
sleep 10
